title:   Ethan Wang
description: Bachelor of Science in Electrical Engineering at UIUC
site_title: 'Ethan Wang Portfolio'

# Build settings
markdown: kramdown
exclude: [vendor/ruby]

# Personalization
email: ethan12wang@gmail.com

# absolute or relative
profile_picture: assets/images/prfp.jpg

# Google Analytics ID
google_analytics: 
